### ISSUE TITLE
透明度

### ISSUE THREAD

**Issue by ZCDu** [KiteAB/dwm#2]
请问如何设置窗口的透明度？我的st在deepin桌面下是可以正常显示透明度的，但是在dwm下面就是全黑
---from 小破站的fan

**Comment by Demon-dream-area** [comment]
请问你的dwm打了alpha补丁了吗，还有透明是需要一个窗口渲染器的，好比picom

**Comment by Demon-dream-area** [comment]
> 请问如何设置窗口的透明度？我的st在deepin桌面下是可以正常显示透明度的，但是在dwm下面就是全黑
> ---from 小破站的fan

那啥，你的dwm打了alpha补丁了吗，还有透明效果还需要一个窗口渲染器，好比picom，可以在脚本里设置开机自启动。

**Comment by ZCDu** [comment]
3Q
